version: "3.8"

services:
  db:
    image: postgres:16
    container_name: pagila_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pagila
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/pagila-schema.sql:/docker-entrypoint-initdb.d/01-pagila-schema.sql
      - ./docker/pagila-data.sql:/docker-entrypoint-initdb.d/02-pagila-data.sql

volumes:
  pgdata:
